version: "2"
linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - revive
    - gosec
    - gocyclo
    - unused
    - misspell
    - gochecknoglobals
    - gochecknoinits

  settings:
    gocyclo:
      min-complexity: 25
    gosec:
      excludes:
        - G501

    revive:
      rules:
        - name: var-naming
          disabled: true

        - name: exported
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
