name: 'Test project'

proxy:
  test:
    - testproject.lndo.site

# Extra plugins loaded within the project
pluginDirs:
  - plugins

services:
  test:
    api: 3
    type: lando

    # SSH user
    meUser: root

    # Expose and terminate TLS at the proxy
    # Does this affect HTTP performance - i.e. I don't get HTTP 2.0 benefits?
    ssl: true
    sslExpose: false

    services:
      image: nginx:stable-alpine
      command: "nginx -g 'daemon off;'"

    build:
      - "echo 'build'"
    build_as_root:
      - "echo 'build_as_root'"
    run:
      - "echo 'run'"
    run_as_root:
      - "echo 'run_as_root'"
