name: 'Test project'
services:
  test:
    image: "nginx:stable-alpine"
    command: "nginx -g 'daemon off;'"
    entrypoint: "/solo-entrypoint.sh"
    volumes:
      # todo: I'd like all target mount files/dirs to go in a solo specific path
      - "./prototype/entrypoint.sh:/solo-entrypoint.sh"
      - "./prototype/build-scripts:/build-scripts:ro"
      - "./prototype/run-scripts:/run-scripts:ro"
    ports:
      - "80:80"
