name: 'Test project'

services:
  test:
    build: .
    command: ['/usr/sbin/nginx', '-g', 'daemon off;']
    #    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - "./cmd/solo-entrypoint:/solo/cmd/solo-entrypoint"
      - "./internal:/solo/internal"
      - "./go.mod:/solo/go.mod"
      - "./go.sum:/solo/go.sum"
