compose_file: docker-compose.yml

services:
  test:
    workflows:
      build:
        - name: 'List files in root'
          command: '/bin/ls'
          working_directory: '/'

        - name: 'List running processes'
          command: '/bin/ps aux'
          working_directory: '/'

      pre_start:
      post_start:

      pre_stop:
      post_stop:

      pre_destroy:
      post_destroy: