x-tools:
  composer:
    description: "Composer for PHP dependency management"
    command: composer
    service: php
    working_directory: /var/www/project

  php:
    description: "PHP interpreter"
    command: php
    service: php
    working_directory: /var/www/project

services:
  nginx:
    build:
        context: .
        dockerfile: ./examples/symfony-webapp/Dockerfile.nginx
    depends_on:
      - php
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    ports:
      - "81:80"
    volumes:
      - "./examples/symfony-webapp/public:/var/www/project/public"
      - "./examples/symfony-webapp/vhost.conf:/etc/nginx/sites-available/default"
      - "./cmd/solo-entrypoint:/solo/cmd/solo-entrypoint"
      - "./internal:/solo/internal"
      - "./go.mod:/solo/go.mod"
      - "./go.sum:/solo/go.sum"

    x-workflows:
      first_pre_start_container:
        timeout: 180s

        steps:
          - name: Update apt
            run: apt update -y

          - name: Install vim
            run: apt install -y vim

  php:
    build:
      context: .
      dockerfile: ./examples/symfony-webapp/Dockerfile.php
    command: /usr/sbin/php-fpm8.4 -FO
    working_dir: /var/www/project
    volumes:
      - "composer:/root/.cache/composer"
      - "./examples/symfony-webapp:/var/www/project"
      - "./examples/symfony-webapp/pool.conf:/etc/php/8.4/fpm/pool.d/www.conf"
      - "./cmd/solo-entrypoint:/solo/cmd/solo-entrypoint"
      - "./internal:/solo/internal"
      - "./go.mod:/solo/go.mod"
      - "./go.sum:/solo/go.sum"

    deploy:
      replicas: 3

    x-workflows:
      first_pre_start_container:
        timeout: 180s

        steps:
          - name: Download composer setup
            run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

          - name: Setup composer
            run: php composer-setup.php

          - name: Remove setup script
            run: php -r "unlink('composer-setup.php');"

          - name: Move composer.phar
            run: mv composer.phar /usr/local/bin/composer

          - name: composer install
            run: composer install

          - name: Update apt
            run: apt update -y

          - name: Install vim
            run: apt install -y vim

  mail:
    profiles: ["mail"]
    build:
      context: .
      dockerfile: ./examples/symfony-webapp/Dockerfile.mail
    entrypoint: /mailpit
    ports:
      - "8025:8025"
    expose:
      - "8025"
      - "1025"

    volumes:
      - "./cmd/solo-entrypoint:/solo/cmd/solo-entrypoint"
      - "./internal:/solo/internal"
      - "./go.mod:/solo/go.mod"
      - "./go.sum:/solo/go.sum"

volumes:
  composer:
