services:
  test:
    build: .
    command: ['/usr/sbin/nginx', '-g', 'daemon off;']
    ports:
      - "80:80"
    volumes:
      - "./cmd/solo-entrypoint:/solo/cmd/solo-entrypoint"
      - "./internal:/solo/internal"
      - "./go.mod:/solo/go.mod"
      - "./go.sum:/solo/go.sum"

    x-workflows:
      first_pre_start:
        steps:
          - name: 'List files in root'
            command: '/bin/ls -lh'
            working_directory: '/'

          - name: 'List running processes'
            command: '/bin/ps aux'
            working_directory: '/'

      pre_start:
        steps:
          - name: 'List running processes'
            command: '/bin/ps aux'
            working_directory: '/'

      post_start:
        steps:
          - name: 'List running processes'
            command: '/bin/ps aux'
            working_directory: '/'

      pre_stop:
        steps:
          - name: 'List running processes'
            command: '/bin/ps aux'
            working_directory: '/'

      pre_destroy:
        steps:
          - name: 'List running processes'
            command: '/bin/ps aux'
            working_directory: '/'
