services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    command: [ "/usr/sbin/nginx", "-g", "daemon off;" ]
    ports:
      - "81:80"

    volumes:
      - "./public:/var/www/project/public"
      - "./vhost.conf:/etc/nginx/sites-available/default"

  php:
    build:
      context: .
      dockerfile: ./Dockerfile.php
    command: /usr/sbin/php-fpm8.4 -FO

    volumes:
      - "composer:/root/.cache/composer"
      - "./:/var/www/project"
      - "./pool.conf:/etc/php/8.4/fpm/pool.d/www.conf"

    deploy:
      replicas: 3

    x-workflows:
      first_pre_start:
        timeout: 180s

        steps:
          - name: Download composer setup
            run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

          - name: Setup composer
            run: php composer-setup.php

          - name: Remove setup script
            run: php -r "unlink('composer-setup.php');"

          - name: Move composer.phar
            run: mv composer.phar /usr/local/bin/composer

          - name: composer install
            run: composer install
            working_directory: /var/www/project

  mail:
    profiles: ["mail"]
    build:
      context: .
      dockerfile: ./Dockerfile.mail
    entrypoint: /mailpit
    ports:
      - "8025:8025"
    expose:
      - "8025"
      - "1025"

volumes:
  composer: