services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    command: [ "/usr/sbin/nginx", "-g", "daemon off;" ]
    ports:
      - "80:80"

    volumes:
      - "./public:/var/www/project/public"
      - "./vhost.conf:/etc/nginx/sites-available/default"

  php:
    build:
      context: .
      dockerfile: ./Dockerfile.php
    command: /usr/sbin/php-fpm8.4 -FO

    volumes:
      - "./:/var/www/project"
      - "./pool.conf:/etc/php/8.4/fpm/pool.d/www.conf"
