name: 'Rebuild project'

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Update packages
        run: sudo apt update

      - name: Install Protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install GRPC/protobuf compiler plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@v1.13.0

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
