name: 'Rebuild project'

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Update packages
        run: sudo apt update

      - name: Install Protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install GRPC/protobuf compiler plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

      - name: Build
        run: make build

      - name: Convert to junit report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest

      - name: Test
        run: | 
          make test 2>&1 | go-junit-report > junit.xml
          gocov convert coverage.txt | gocov-xml > coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          files: ./junit.xml, ./coverage.xml

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
